### ISSUE TITLE
Both `go build` and `go run main.go` fail with same error

### ISSUE THREAD

**Issue by tb0hdan** [teros0/cservices#3]

**Comment by tb0hdan** [comment]
main.go:5:2: cannot find package "cservices/ingestor" in any of:
	/Users/user/WORK/GOPATH/src/github.com/teros0/cservices/vendor/cservices/ingestor (vendor tree)
	/usr/local/Cellar/go/1.11.1/libexec/src/cservices/ingestor (from $GOROOT)
	/Users/user/WORK/GOPATH/src/cservices/ingestor (from $GOPATH)
main.go:6:2: cannot find package "cservices/storage" in any of:
	/Users/user/WORK/GOPATH/src/github.com/teros0/cservices/vendor/cservices/storage (vendor tree)
	/usr/local/Cellar/go/1.11.1/libexec/src/cservices/storage (from $GOROOT)
	/Users/user/WORK/GOPATH/src/cservices/storage (from $GOPATH)

**Comment by teros0** [comment]
fixed
